# Generated by Django 5.0.3 on 2024-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='added_to_wish_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='siblings',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(null=True),
        ),
    ]
