# Generated by Django 5.0.3 on 2024-06-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_to_wish_list',
        ),
    ]
