# Generated by Django 5.0.3 on 2024-04-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo_home',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.RemoveField(
            model_name='contactinfo_home',
            name='textt',
        ),
    ]
