# Generated by Django 5.0.3 on 2024-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactinfo_home_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo_home',
        ),
    ]
